name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Roda diariamente à meia-noite
  workflow_dispatch: # Permite execução manual

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        outputs: |
          dist/github-snake.svg
          dist/github-snake-dark.svg?palette=github-dark
          dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Commit & Push
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Generate GitHub Snake Game'
          add: 'dist'
